Incorrect
Options: "never"

async function invalidNever1() {
  try {
    return await Promise.resolve('try');
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Returning an awaited promise is not allowed in this context.
  } catch (e) {}
}

async function invalidNever2() {
  return await Promise.resolve('try');
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ Returning an awaited promise is not allowed in this context.
}

async function invalidNever3() {
  return await 'value';
         ~~~~~~~~~~~~~ Returning an awaited value that is not a promise is not allowed.
}
