Correct

Promise.reject(new Error('I will reject!')).catch((err: unknown) => {
  console.log(err);
});
